leftnav:
- identifier: bb4812a8-a1be-ff49-20b9-d5f015f8554d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: a14ea93e-03c6-f6a7-b0e0-4ea4e92c6c01
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 70a39496-8da0-5909-6ed5-33b7578618a3
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 96e8bfeb-9a0e-5f79-ee02-baab9d4ebf3e
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: b30f86be-3fed-fadb-d7db-0c8a461039b6
  name: Projects
  pageRef: /pages/projects/
  weight: 50
